<?php

namespace Appsthergo\API;

require "languages/Lang_ES.php";

class Lang {

    public $lang;

    //**************************************************************
    // TEXT ID
    //**************************************************************
    const MSJ_ERROR_CREATE_FORM = "MSJ_ERROR_CREATE_FORM";
    const CREATE_USER_FORM_TEXT_INPUT_NAME1 = "CREATE_USER_FORM_TEXT_INPUT_NAME1";
    const CREATE_USER_FORM_TEXT_INPUT_NAME2 = "CREATE_USER_FORM_TEXT_INPUT_NAME2";
    const CREATE_USER_FORM_TEXT_INPUT_LASTNAME = "CREATE_USER_FORM_TEXT_INPUT_LASTNAME";
    const CREATE_USER_FORM_TEXT_INPUT_EMAIL = "CREATE_USER_FORM_TEXT_INPUT_EMAIL";
    const CREATE_USER_FORM_TEXT_INPUT_PASSWORD = "CREATE_USER_FORM_TEXT_INPUT_PASSWORD";
    const CREATE_USER_FORM_TEXT_INPUT_REPEAT_PASSWORD = "CREATE_USER_FORM_TEXT_INPUT_REPEAT_PASSWORD";
    const CREATE_USER_FORM_ERROR_INPUT_NAME = "CREATE_USER_FORM_ERROR_INPUT_NAME";
    const CREATE_USER_FORM_ERROR_INPUT_LASTNAME = "CREATE_USER_FORM_ERROR_INPUT_LASTNAME";
    const CREATE_USER_FORM_ERROR_INPUT_EMAIL = "CREATE_USER_FORM_ERROR_INPUT_EMAIL";
    const CREATE_USER_FORM_ERROR_INPUT_PASSWORD = "CREATE_USER_FORM_ERROR_INPUT_PASSWORD";
    const CREATE_USER_FORM_ERROR_INPUT_REPEAT_PASSWORD = "CREATE_USER_FORM_ERROR_INPUT_REPEAT_PASSWORD";
    const CREATE_USER_FORM_SUBMIT = "CREATE_USER_FORM_SUBMIT";
    const CREATE_USER_FORM_ERROR_EMAIL_EXISTS = "CREATE_USER_FORM_ERROR_EMAIL_EXISTS";
    const CREATE_USER_FORM_MSJ_SUCCESS = "CREATE_USER_FORM_MSJ_SUCCESS";
    const CREATE_USER_FORM_DESCRIPTION = "CREATE_USER_FORM_DESCRIPTION";
    const CREATE_USER_FORM_TITLE_SUCCESS = "CREATE_USER_FORM_TITLE_SUCCESS";
    const LOGIN_FORM_INPUT_PASSWORD = "LOGIN_FORM_INPUT_PASSWORD";
    const LOGIN_FORM_INPUT_EMAIL = "LOGIN_FORM_INPUT_EMAIL";
    const LOGIN_FORM_CHECK_REMEMBER = "LOGIN_FORM_CHECK_REMEMBER";
    const LOGIN_FORM_LINK_RECOVERY = "LOGIN_FORM_LINK_RECOVERY";
    const LOGIN_FORM_SUBMIT = "LOGIN_FORM_SUBMIT";
    const LOGIN_FORM_DESCRIPTION_LABEL = "LOGIN_FORM_DESCRIPTION_LABEL";
    const LOGIN_FORM_MSJ_LOGOUT = "LOGIN_FORM_MSJ_LOGOUT";
    const LOGIN_FORM_SEND_EMAIL_CONFIRMATION = "LOGIN_FORM_SEND_EMAIL_CONFIRMATION";
    const LOGIN_FORM_MSJ_FAIL_CONFIRMATION = "LOGIN_FORM_MSJ_FAIL_CONFIRMATION";
    const LOGIN_FORM_MSJ_FAIL_LOGIN = "LOGIN_FORM_MSJ_FAIL_LOGIN";
    const LOGIN_FORM_FAIL_RECOVERY_PASSWORD = "LOGIN_FORM_FAIL_RECOVERY_PASSWORD";
    const LOGIN_FORM_MSJ_RECOVERY_PASSWORD = "LOGIN_FORM_MSJ_RECOVERY_PASSWORD";
    const LOGIN_FORM_MSJ_CONFIRMATION_MAIL = "LOGIN_FORM_MSJ_CONFIRMATION_MAIL";
    const RECOVERY_FORM_TITLE = "RECOVERY_FORM_TITLE";
    const RECOVERY_FORM_INPUT_EMAIL = "RECOVERY_FORM_INPUT_EMAIL";
    const RECOVERY_FORM_SUBMIT = "RECOVERY_FORM_SUBMIT";
    const RECOVERY_FORM_MSJ_ACCOUNT_INACTIVE_TITLE = "RECOVERY_FORM_MSJ_ACCOUNT_INACTIVE_TITLE";
    const RECOVERY_FORM_MSJ_ACCOUNT_INACTIVE = "RECOVERY_FORM_MSJ_ACCOUNT_INACTIVE";
    const RECOVERY_FORM_MSJ_FAIL_EMAIL="RECOVERY_FORM_MSJ_FAIL_EMAIL";
    const RECOVERY_FORM_MSJ_SEND_EMAIL_TITLE="RECOVERY_FORM_MSJ_SEND_EMAIL_TITLE";
    const RECOVERY_FORM_MSJ_SEND_EMAIL="RECOVERY_FORM_MSJ_SEND_EMAIL";
    
    public function __call($name, $args) {
        $text = constant('Appsthergo\API\Lang\Lang_' . $this->lang . '::' . $args[0]);

        foreach ($args[1] as $var => $value)
            $text = str_replace(":" . $var, $value, $text);

        return $text;
    }

    /** Print a text with his id
     * 
     * @param type $stringId
     * @param type $vars Array of var that replace into text
     * @return type
     */
    public function printText($stringId, $vars = array()) {
        return $this->out($stringId, $vars);
    }

}
